{% set name = "apache-airflow-providers-jdbc" %}
{% set version = "4.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_jdbc-{{ version }}.tar.gz
  sha256: d92ae7c5f925778475493117a9aa315d9c19d7266d300445b9b247b4b7795a3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    - jaydebeapi >=1.1.1

test:
  imports:
    - airflow.providers.jdbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-jdbc for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/jdbc/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-jdbc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
