{% set name = "apache-airflow-providers-jdbc" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_jdbc-{{ version }}.tar.gz
  sha256: 5ec713ae6d009a900a4b67a450311ff1733be5e2cff03055c321831ea8de45de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-common-sql >=1.20.0
    - jaydebeapi >=1.1.1

test:
  imports:
    - airflow.providers.jdbc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-jdbc for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-jdbc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
