{% set name = "apache-airflow-providers-jdbc" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-jdbc-{{ version }}.tar.gz
  sha256: 2e4411d805e9d6bebf40e5feeab7e9bf4ec6f9a0f7b52361cc5c8cc13ea6c41a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.4.0
    - jaydebeapi >=1.1.1

test:
  imports:
    - airflow.providers.jdbc
    - airflow.providers.jdbc.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-jdbc package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-jdbc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
